language: python
# give up the ability to use 'sudo' in exchange for getting access to
# the newer/faster/better-scaling travis infrastructure
sudo: false
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

install:
- pip install -U pip setuptools wheel nose
- python setup.py bdist_wheel
- pip install dist/*

script:
# Don't run tests from the source directory root, in order to make sure that
# we're testing the installed metamodule
- cd tests
- nosetests .
